name: Install and test stryker-log-ignorer
on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  strykerlogignorer:
    name: NodeJS-CI-libs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm install --ignore-scripts
      - name: Check for formatting issues
        run: npm run checkformat
      - name: Check for linting issues
        run: npm run lint
      - name: Check types
        run: npm run check
      - name: Run tests
        run: npm test
